from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "assets" / "lbt-share-card.png"
W, H = 1200, 630

def font(size, bold=False):
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
    ]
    for candidate in candidates:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    return ImageFont.load_default()

img = Image.new("RGB", (W, H), "#0e0b09")
draw = ImageDraw.Draw(img)

# 深いチャコール背景に、LBTの共有シートを連想させる薄い機械・時計モチーフを敷く。
for i in range(0, W + H, 38):
    draw.line((i, 0, 0, i), fill="#16110f", width=1)
    draw.line((W - i, H, W, H - i), fill="#16110f", width=1)
draw.ellipse((760, -130, 1360, 470), outline="#4b3329", width=4)
draw.ellipse((835, -55, 1285, 395), outline="#2c211d", width=3)
draw.ellipse((920, 30, 1200, 310), outline="#6d4e29", width=2)
for x in range(778, 1185, 32):
    draw.line((x, 170, x + 11, 194), fill="#6d4e29", width=4)

# 外枠・強調線。
draw.rounded_rectangle((48, 44, W - 48, H - 44), radius=12, outline="#60482f", width=2)
draw.line((82, 126, 722, 126), fill="#d4af5f", width=3)
draw.line((82, 130, 462, 130), fill="#c8352b", width=5)

mono = font(20, bold=True)
title = font(58, bold=True)
subtitle = font(26, bold=True)
micro = font(17)

draw.text((84, 78), "LBT / SHARE SHEET", fill="#d4af5f", font=mono)
draw.text((82, 168), "LIMBUS BUILD", fill="#f2ece1", font=title)
draw.text((82, 238), "TERMINAL", fill="#f2ece1", font=title)
draw.text((86, 327), "PERSONA PRESET", fill="#d4af5f", font=subtitle)
draw.text((86, 372), "CCFOLIA / TRPG CHARACTER SHEET", fill="#c6bba9", font=mono)

# 共有シートらしいミニステータス群。個人データは画像に含めず、タイトルと説明で動的に伝える。
cards = [(82, 452, "HP", "—"), (245, 452, "SAN", "—"), (408, 452, "SPD", "—")]
for x, y, label, value in cards:
    draw.rounded_rectangle((x, y, x + 136, y + 96), radius=6, fill="#191412", outline="#49362b", width=2)
    draw.text((x + 15, y + 14), label, fill="#a89e8c", font=mono)
    draw.text((x + 15, y + 46), value, fill="#eecf8a", font=font(31, bold=True))

draw.text((84, 580), "Generated by LIMBUS BUILD TERMINAL", fill="#8f8274", font=micro)
draw.text((785, 535), "OPEN THE SHEET", fill="#d4af5f", font=font(22, bold=True))
draw.line((785, 575, 1085, 575), fill="#c8352b", width=4)

OUT.parent.mkdir(parents=True, exist_ok=True)
img.save(OUT, "PNG", optimize=True)
print(OUT)
